### PR TITLE
Change `CColor` to be opaque (alpha=255) instead of transparent

### PR DESCRIPTION
**Pull request by Jarod42**
Should fix issue #596 with font display

### CODE REVIEW

**Comment by ipochto** [comment]
Still broken (
2024-02-25-184104_2560x1440_scrot
2024-02-25-184112_2560x1440_scrot

**Comment by zzam** [comment]
Fixes it for me under linux:
with current master https://github.com/Wargus/stratagus/commit/f584f2cc4ba9aba5f4eb5aadd793b59578228206
wargus-master-bad-font

with color_alpha https://github.com/Wargus/stratagus/commit/38c813375c46be98ee83d7fdc5b6ee8367609f12
wargus-color_alpha-good

This makes the menus usable again.

Mission briefing is fine:
wargus-color_alpha-briefing-good

Only the picturestep in the campagin is still broken. It does not show the image:
wargus-color_alpha-picturestep-not-visible

**Comment by ipochto** [comment]
Fixed for me too.

**Comment by Jarod42** [comment]
@zzam: black screen should be fixed by #616.
submodule update...

**Pull request merged**
