### PR TITLE
add minimal support for attract/demo mode

### PR DESCRIPTION
**Pull request by talas**
in wargus, this means watching 2 computers fight eachother.
any interaction will end the demo.

Could also create a IsDemoMode() helper instead of the "weird?" (GameRunning && ThisPlayer->Type == PlayerNobody) check.

The term demo is a bit confusing here though, as it has nothing to do with the shareware version.

### CODE REVIEW

**Comment by talas** [comment]
To test the changes, you can use this in wargus:
https://github.com/Wargus/wargus/pull/306

**Comment by timfel** [comment]
Sorry, I dropped the ball on this. This is cool stuff! I agree, if you could create a helper function isDemoMode or such, it would make the code easier to read. Could you do that?

**Comment by timfel** [comment]
I will merge the wargus change after this one, because the way the build works master binaries are created immediately with the Stratagus master, so this here has to be merged first.

**Comment by timfel** [comment]
Also, if you're interested in working some more on Wargus and Stratagus, I'd be happy to add you to the dev team, just let me know. You can also ping me on Gitter of you want to discuss plans or changes more directly

**Comment by talas** [comment]
Thanks for the offer, I'll consider it.
Note that I'm currently more interested in making a rebalanced/modernized esports wargus than original gameplay. Which sounds like fork material I guess. But, I'll be happy to upstream anything that makes sense.

**Pull request merged**
