### PR TITLE
Fix372 win7

### PR DESCRIPTION
**Pull request by psa-jforestier**
Fixing issue https://github.com/Wargus/wargus/issues/372 to make Stratagus work on Windows Seven (including the 32bits version).
Must be strarted with `-g -W` flags to not use OpenGL and have a Window.

Also fixing some crashes because using unintialized string buffer.

### CODE REVIEW

**Comment by timfel** [comment]
Thanks for those fixes! I added a the bit to automatically force software rendering and windowed mode when we get into the Windows 7 and older branches, so that hopefully Win7 will work again with the next bugfix release.

**Comment by c-sanchez** [comment]
I would like to know how much the engine has improved and how well it works for Starcraft now.
As far as I can see, there is not much information about it.

**Comment by timfel** [comment]
@c-sanchez no one has worked on the Stargus mod since 2017. It's not compatible with the current engine version. One feature in the engine that is missing, but that @ipochto is interested in is the height level for map tiles. Besides that, many things could already be made to work with lua scripting, but it's a lot of work. Since no one has stepped up to do it, I would consider Stargus abandoned for now.

**Comment by c-sanchez** [comment]
Ah, I understand that it doesn't work with the current starcraft engine, especially since it has probably changed a lot with Remastered.
However, it would be great if at some point it would be fully compatible with the latest classic (and now free) version of startcraft, 1.16.1
But I guess I'm for the same reason you say it's in a very early stage of development and now abandoned :(
A shame really, it would be great now that Starcraft is, partially, a free game.

**Comment by timfel** [comment]
@c-sanchez i didn't mean remastered - Stargus is no longer compatible with the current release of the Stratagus engine. It's really abandoned im the state of 2017

**Comment by dmitry-bikbaev** [comment]
> 
> 
> Thanks for those fixes! I added a the bit to automatically force software rendering and windowed mode when we get into the Windows 7 and older branches, so that hopefully Win7 will work again with the next bugfix release.

This 'next bugfix release' you've mentioned isn't 3.1.2 ? I still have the same problem at Win7 x64 with Wargus 3.1.2. I confirm a proposed by @psa-jforestier workaround to run Wargus portable 3.1.2 through 'stratagus.exe -g -W -a -d c:\Wargusdata', is working great.

**Comment by psa-jforestier** [comment]
3.1.2 seems to not contains this patch. Try the 3.1.3 pre-version : 
https://github.com/Wargus/Wargus/releases/master-builds

**Comment by dmitry-bikbaev** [comment]
Tried 3.1.3. Still the same. Product Name: Wargus / Product Version: 3.1.3 / Crash Address: 766CDF15 / Crash Address (Relative): KERNELBASE.dll!ReadFile+0x138 / Exception Code: C0000005 / Exception Description: Access Violation - Failed to access 00000000 memory address (Write Access)

**Comment by timfel** [comment]
3.1.2 includes this patch. It's simply that the software renderer seems not to be automatically applied.

**Comment by dmitry-bikbaev** [comment]
So how to run Wargus.exe with software renderer applied? May be exists such parameter of Wargus.exe?

**Comment by timfel** [comment]
> So how to run Wargus.exe with software renderer applied? May be exists such parameter of Wargus.exe?

wargus.exe accepts the same parameters as stratagus.exe

**Pull request merged**
