### PR TITLE
Cleanup repo from maemo code

### PR DESCRIPTION
**Pull request by KroArtem**
I saw you've removed some words about Maemo support in some commits so I thought this could be done elsewhere in the code. If it is so, I'll continue removing all maemo stuff and will add it to this PR.

### CODE REVIEW

**Comment by timfel** [comment]
Sure, I don't think Maemo support is still relevant. If you want to get it out, go for it :+1:

**Comment by a-detiste** [comment]
The big Maemo block in debian/rules can also go if you're intterrested into cleaning this.

**Comment by KroArtem** [comment]
yup, will do it, just decided to ask whether it's needed.

**Comment by KroArtem** [comment]
Done.

**Comment by timfel** [comment]
Looks good :+1:

**Pull request merged**
