### PR TITLE
War1gus fix

### PR DESCRIPTION
**Pull request by Jarod42**

### CODE REVIEW

**Comment by ipochto** [comment]
Somehow get this:
```
stratagus/src/include/video.h:44:10: fatal error: guichan/sdl/sdlimage.hpp: No such file or directory
[build]    44 | #include <guichan/sdl/sdlimage.hpp>
[build]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Jarod42** [comment]
Have you updated third-party? issue with submodules and switching branch is that it need extra flags to also apply to submodules :/

**Comment by ipochto** [comment]
You're right.
Updated.
Now have this:
```
[build] stratagus/third-party/guichan/src/sdl/sdlinput.cpp:55:17: error: ‘uint32_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
[build]    55 |     static std::uint32_t utf8ToUnicode(const char* text)
[build]       |                 ^~~~~~~~
[build]       |                 wint_t
[build] stratagus/third-party/guichan/src/sdl/sdlinput.cpp: In member function ‘virtual void gcn::SDLInput::pushInput(SDL_Event)’:
[build] stratagus/third-party/guichan/src/sdl/sdlinput.cpp:145:31: error: ‘utf8ToUnicode’ was not declared in this scope
[build]   145 |               keyInput.setKey(utf8ToUnicode(event.text.text));
[build]       |                               ^~~~~~~~~~~~~
```

**Comment by Jarod42** [comment]
Shit, missing `#include <cstdint>` on linux ... :-/

**Pull request merged**
